### ISSUE TITLE
Can't overlay administrative boundary on GOES timelapse

### ISSUE THREAD

**Issue by gsjlogie** [giswqs/streamlit-geospatial#10]
Hi there. I've been trying to create a GOES timelapse, and overlay some geojson information, but every time I try it I get the following message: "Something went wrong, either the ROI is too big or there are no data available for the specified date range. Please try a smaller ROI or different date range."

When I run without an administrative boundary it works fine, so it's not the ROI size. I tried a custom administrative boundary, but also tried the default ones (Countries and Continents). None work. I've attached screenshots of my settings.

Fantastic app btw. Very cool stuff.

![Timelapse_settings_1](https://user-images.githubusercontent.com/15931565/143056010-bd39ca63-381c-421e-8ddf-4e9807be6c3a.png)
![Timelapse_settings_2](https://user-images.githubusercontent.com/15931565/143056195-392a6647-9aaa-4a12-83d8-fda65fe56bd3.png)

**Comment by giswqs** [comment]
Thank you for reporting. It is probably a projection issue. I will look into it.

**Comment by giswqs** [comment]
I just tested it and found that the ROI is indeed a big large. Keep in mind that adding the administrative boundary will result in more data requested from GEE. It can sometimes exceed the data limit even though you were able to create one without the administrative boundary.  

See the example below for a smaller ROI with administrative boundaries added. 

![goes](https://user-images.githubusercontent.com/5016453/143531614-cd7e8b57-2887-45d4-8aee-304c68b6771d.gif)

**Comment by gsjlogie** [comment]
Very sorry I never followed up on this. Thanks very much for looking at it. That makes sense to me. I wish there was an easy way to know when you're requesting too much data, but I expect that'd be a hard thing to know, since I imagine it'd vary based on AOI size, data type, date range, etc.

**Comment by giswqs** [comment]
You are correct. It is difficult to know the data volume until GEE throws a memory error. You can play with the parameters and get a rough idea how big the roi with different data range and temporal frequency.
