### ISSUE TITLE
Running ee_authenticate(...).

### ISSUE THREAD

**Issue by tnmthai** [giswqs/streamlit-geospatial#100]
I have tried many times but have still been stuck for **ee_authenticate**.
I created EARTHENGINE_TOKEN="4/1AfgeXvvVnaskgu............." in Secrets.

Any ideas? Thanks

**Comment by giswqs** [comment]
The token should look like this:

![image](https://user-images.githubusercontent.com/5016453/204970101-4573a0cb-e6a6-4b1f-824b-fe718fa128b3.png)

**Comment by MuhammedM294** [comment]
I had this problem last week and solved it by setting the authentication mode to "gcloud". I used the ee_initialize function from geemap/common.

geemap.ee_initialize(auth_mode='gcloud')
