### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by GopalKrishna-India** [giswqs/streamlit-geospatial#101]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://geospatial.streamlit.app/giswqs/streamlit-geospatial/Home.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by MuhammedM294** [comment]
You can just reboot the app.
