### ISSUE TITLE
geemap Map's layers in streamlit

### ISSUE THREAD

**Issue by MuhammedM294** [giswqs/streamlit-geospatial#102]
Recently, the map layers don't show in the app. The map frames and controls are okay, but the layers have a problem. I tried to install previous versions of geemap and leafmap, but still have the same issue.

**Comment by giswqs** [comment]
Try out https://geospatial.streamlit.app/Earth_Engine_Datasets. It works fine.

**Comment by MuhammedM294** [comment]
Thank you for your reply! The problem with the basemap itself not just the gee layers. I've tested it in jupyter notebook and it works fine, but within streamlit, either locally or on the cloud doesn't work.

**Comment by giswqs** [comment]
Share the link to your source code? Otherwise, there is nothing I can do about it as I can't reproduce the issue

**Comment by giswqs** [comment]
Did you try out the geemap.Map() class directly with streamlit? If geemap.Map() works with streamlit but not your own inherited map class, then it is your package issue rather than a geemap issue.

**Comment by giswqs** [comment]
It appears that you are using the ipyleaflet plotting backend. You should use folium instead. Ipyleaflet does not work well with streamlit

**Comment by MuhammedM294** [comment]
Solved Thanks!
