### ISSUE TITLE
Attempt to deploy streamlit thwarted at ee.Authenticate() - missing gcloud?

### ISSUE THREAD

**Issue by frizatch** [giswqs/streamlit-geospatial#107]
Greetings! I too, like issue #94, am trying to follow that [blog](https://blog.streamlit.io/creating-satellite-timelapse-with-streamlit-and-earth-engine/#how-to-deploy-an-earth-engine-app-to-streamlit-cloud) and create a working app by forking that repo, but I am getting stuck earlier at the 'ee.Authenticate()' step. I get an error that ends with:

'Exception: gcloud command not found. Please ensure that gcloud is installed.'
'More information: https://developers.google.com/earth-engine/guides/python_install'

I eventually landed here but I'm feeling a bit lost as I don't think this is correct (I'm building environments in Anaconda): https://cloud.google.com/sdk/docs/install

Also, I tried this package but it is no longer available from conda-forge according to my install attempt:
https://anaconda.org/conda-forge/google-cloud-sdk

Have others see this error? Do you have a quick hint as to where I might look to fix the authentication issue with gcloud?

Thanks much!

**Comment by giswqs** [comment]
See https://github.com/giswqs/streamlit-geospatial/issues/94

**Comment by frizatch** [comment]
Thanks, I will look at #94 again! I had the impression I was hitting a different issue as I wasn't able to get as far as that person since ee.Authenticate couldn't initiate.
