### ISSUE TITLE
streamlit.gishub.org U.S. Real Estate Data and Market Trends error

### ISSUE THREAD

**Issue by Niko-La** [giswqs/streamlit-geospatial#13]
Hi on the hosted site the demo for us real estate is showing the following error

![image](https://user-images.githubusercontent.com/14004559/144949885-99e16161-0f3c-441c-8c4c-067282e5852c.png)

**Comment by giswqs** [comment]
It seems the new [realtor.com data](https://www.realtor.com/research/data) are messed up. I have temporarily fixed it by using some older data.
