### ISSUE TITLE
'Map' object has no attribute 'add_points_from_xy'

### ISSUE THREAD

**Issue by piedacoulisse2** [giswqs/streamlit-geospatial#17]
Hello,

Thank you for the job, the programs seems perfect for my projet.
However, I have a problem with the installation. I try several solution (pip, conda) but I have this message : 

![image](https://user-images.githubusercontent.com/74360897/146834442-613783c5-b19c-43d1-a70d-bfff129b85b8.png)

When i try to understand, I have this message : 'Map' object has no attribute 'add_points_from_xy'

Best regards, 

Piedacoulisse

**Comment by giswqs** [comment]
Some of the new functions have not been related to PyPI yet. Try `pip install git+git://github.com/giswqs/leafmap`

**Comment by piedacoulisse2** [comment]
Thank but it does not work. Do you have pull the release ?

**Comment by giswqs** [comment]
Are you running the app locally or on Streamlit Cloud?

**Comment by piedacoulisse2** [comment]
Locally, I try with severals configuration, the last one is : 

- WSL2 Ubuntu 20.4 Conda env 

Config installation : 
```
conda create -n geo python=3.8
conda activate geo
conda install geopandas
conda install mamba -c conda-forge
pip install git+git://github.com/giswqs/leafmap 
mamba install geemap keplergl palettable localtileserver streamlit streamlit-bokeh-events gdal -c conda-forge
```
I obtain : 

![image](https://user-images.githubusercontent.com/74360897/146930477-b2bff2e7-7276-48d3-aa3d-2c2f82e4a9b6.png)

Or 

![image](https://user-images.githubusercontent.com/74360897/146930981-8bbae3e3-7639-4416-820a-9bd2c3ea3a2c.png)


The code is for test.py

```
import streamlit as st
from multiapp import MultiApp
from apps import (
    xy,
    carte_simple,
)

st.set_page_config(layout="wide")


apps = MultiApp()

# Add all your application here

apps.add_app("Nouvelle carte",carte_simple)
apps.add_app("Add Points from XY", xy.app)


# The main app
apps.run()

```
And for carte_simple.py

```
import leafmap.foliumap as leafmap
import pandas as pd
import streamlit as st


m = leafmap.Map()
data = 'https://raw.githubusercontent.com/giswqs/leafmap/master/examples/data/us_cities.csv'
m.add_points_from_xy(data, x="longitude", y="latitude")
```

**Comment by giswqs** [comment]
Did you clone my repo and run it locally? You also need `pip install git+git://github.com/giswqs/geemap`

If my repo works fine on your computer but not your own code, then the issue is probably caused by your app setup, not geemap/leafmap.

**Comment by piedacoulisse2** [comment]
In fact, it was my code that did not work. Thank for your help and the nice project. 
Now it works for me. 

The configuration is : 

```
conda create -n geo python=3.8
conda activate geo
conda install geopandas
conda install mamba -c conda-forge
pip install git+git://github.com/giswqs/leafmap 
mamba install geemap keplergl palettable localtileserver streamlit streamlit-bokeh-events gdal -c conda-forge
```

And 
`git clone https://github.com/giswqs/streamlit-geospatial.git`

**Comment by giswqs** [comment]
Glad to know that it helped.
