### ISSUE TITLE
Add positioning feature

### ISSUE THREAD

**Issue by fiorins** [giswqs/streamlit-geospatial#2]
Hi, it will be useful if on the map there would be a button to localize my position, cause everytime I clean the map, it return on Pucallpa (I'm talking about "Create Timelapse" but I'm sure it will be useful for other sections too).  Cheers

**Comment by giswqs** [comment]
This feature has been implemented. Try it out. 

![](https://i.imgur.com/reFI4US.png)

**Comment by giswqs** [comment]
It seems the button in the embedded HTML is not working properly. Try this direct link

https://share.streamlit.io/giswqs/streamlit-geospatial/app.py?page=Create+Timelapse

**Comment by fiorins** [comment]
Ok, that's awesome, idk if I can help you, did you develop this website with Flask ?

**Comment by giswqs** [comment]
It was developed using Python and deployed on [streamlit cloud](https://streamlit.io/cloud). No flask. Check the source in this repo.

**Comment by giswqs** [comment]
The app now has a button for retrieving the device location. Try it out: https://streamlit.gishub.org

![](https://i.imgur.com/7FCUJHN.gif)
