### ISSUE TITLE
Feature request - Ocean Colour/temperature

### ISSUE THREAD

**Issue by giswqs** [giswqs/streamlit-geospatial#21]
### Discussed in https://github.com/giswqs/streamlit-geospatial/discussions/20

<div type='discussions-op-text'>

<sup>Originally posted by **ChrisHarrod** December 30, 2021</sup>
Firstly, many thanks for a great application!

Further to my request on Twitter, I would like to ask if it is possible to include some oceanographic options such sea surface temperature  or chlorophyll a concentrations. As requested, I looked in the Google Earth Engine catalogue and the products most used by people looking to show variation over time are things like the Sentinal https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S3_OLCI or Modis https://developers.google.com/earth-engine/datasets/catalog/NASA_OCEANDATA_MODIS-Aqua_L3SMI

All the best
Chris

</div>

**Comment by giswqs** [comment]
@ChrisHarrod Thank you for the suggestion. I should be able to implement early next week. Stay tuned.

**Comment by ChrisHarrod** [comment]
Now that is service!!

**Comment by giswqs** [comment]
Source code has been implemented in [geemap](https://github.com/giswqs/geemap). Will add to the streamlit web app soon. 

```python
import geemap
geemap.ee_initialize()
title = "Gulf of Mexico - Sea Surface Temperature", 
geemap.modis_ocean_color_timelapse("Aqua", "2020-01-01", "2021-01-01", bands=["sst"], frequency="week", title=title, out_gif="modis.gif")
```

https://github.com/giswqs/geemap/blob/0b5b51cd90a30819a55112f410921a325e94caf1/geemap/timelapse.py#L3121-L3130

![](https://i.imgur.com/RU0XSyc.gif)
![modis](https://user-images.githubusercontent.com/5016453/147801832-c909de2c-8a60-45c5-9750-6cfebb56c854.gif)

**Comment by giswqs** [comment]
It has been implemented. Try it out at https://streamlit.gishub.org

![image](https://user-images.githubusercontent.com/5016453/147803146-016f19ff-763f-4973-9210-1b134e154e1e.png)

**Comment by giswqs** [comment]
A colorbar will be added to the timelapse soon. #24 
```python
import geemap
import geemap.colormaps as cm 
geemap.save_colorbar(vis_params={'min': 20, "max":40, 'palette': cm.get_palette("coolwarm")}, tick_size=12, label="Surface temperature")
```

![image](https://user-images.githubusercontent.com/5016453/147823877-f8605385-96b7-4a95-9e9c-8a88d62b8841.png)

**Comment by ChrisHarrod** [comment]
I am in awe at your speed! Many thanks for this!

**Comment by giswqs** [comment]
A colorbar can now be added automatically based on the selected palette. Try it out at https://streamlit.gishub.org. Feel free to let me know if you run into any issues. 

![](https://i.imgur.com/P2FRgED.gif)

**Comment by ChrisHarrod** [comment]
Is there anyway we can control the range of temperatures shown (e.g. set thresholds for min and max values)?

For instance in my local bay, it remains a single colour over time (as the variation is relatively limited compared to your example)

Cheers Quisheng!
Chris

**Comment by giswqs** [comment]
I just added an option for entering visualization parameters. You can enter something like `{'min': 23, 'max': 32}`. See the sceenshot below. The colorbar will change accordingly. 

![Screenshot_20220103_155416](https://user-images.githubusercontent.com/5016453/147979284-7f9921ed-0724-4d1b-bb9d-17617c4a6937.png)

![modis](https://user-images.githubusercontent.com/5016453/147979423-e84fd6d4-b967-479c-a775-911bf889f0fc.gif)

**Comment by ChrisHarrod** [comment]
Thanks – will have a go.

Chris
