### ISSUE TITLE
Resetting the Popup Boxes

### ISSUE THREAD

**Issue by GOItPadma** [giswqs/streamlit-geospatial#23]
I started using the app to create Timelapse of various satellite images and it has been very useful in understanding the spatiotemporal changes. I would like to give a suggestion that may enhance better user experience.

![Screenshot (4)](https://user-images.githubusercontent.com/74313275/147817039-2f556b0e-2674-4d09-af29-c61e7d7ed491.png)

While drawing polygon, for each click, the lat-long popup box creates an obstacle. Each time the box needs to be closed to select the next point. Moreover, the **Finish | Delete Last Point | Cancel** box hides some areas. Zooming in sometimes helps in this issue, but I think shortening or realigning these two boxes can make it easier in selecting the AOI.

**Comment by giswqs** [comment]
Thank you for the suggestion. Thank lat-lon popup has been disabled. I have no control over the **Finish | Delete Last Point | Cancel box**. You can use the Fullscreen button to make the map view larger if needed.
