### ISSUE TITLE
Timelapse not working

### ISSUE THREAD

**Issue by ACBADEA** [giswqs/streamlit-geospatial#3]
I can't run Timelapse

AttributeError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs.
Traceback:
File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
File "/app/streamlit-geospatial/app.py", line 37, in <module>
    apps.run()
File "/app/streamlit-geospatial/multiapp.py", line 63, in run
    functions[titles.index(title)]()
File "/app/streamlit-geospatial/apps/timelapse.py", line 232, in app
    out_gif = geemap.landsat_ts_gif(

**Comment by giswqs** [comment]
Thanks for reporting. The bug has been fixed. Please try again.

**Comment by ACBADEA** [comment]
Thank you, it's ok now. 

    On Sunday, November 7, 2021, 02:03:55 PM GMT+2, Qiusheng Wu ***@***.***> wrote:  
 
 


Thanks for reporting. The bug has been fixed. Please try again.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
