### ISSUE TITLE
Interactive map plotting using streamlit-geospatial

### ISSUE THREAD

**Issue by Spiruel** [giswqs/streamlit-geospatial#31]
Hi,

I'm creating an educational web app using streamlit-geospatial. Please could you let me know if it's possible to capture lat,lon coordinates from markers/or from user mouseclicks, to then poll Google Earth Engine and plot a time series graph?

I've been following the documentation here https://geemap.org/notebooks/geemap_and_ipyleaflet/?h=user#capture-user-inputs but this doesn't seem to apply with the static Streamlit maps.

Thanks

**Comment by giswqs** [comment]
This is my most wanted feature. Unfortunately, streamlit does not support ipyleaflet. Once you convert the ipyleaflet map to HTML to be displayed in streamlit, you lose all the bi-directional functionality. I am not aware of any mapping library that supports bi-directional functionality in streamlit at the moment.
