### ISSUE TITLE
您好 这个网站进不去啊

### ISSUE THREAD

**Issue by zhoubochen** [giswqs/streamlit-geospatial#34]

**Comment by giswqs** [comment]
Thanks for reporting. The app has been rebooted. It should be working now.

**Comment by zhoubochen** [comment]
Thanks for your reply. I see




---- 回复的原邮件 ----
| 发件人 | Qiusheng ***@***.***> |
| 日期 | 2022年02月24日 13:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [giswqs/streamlit-geospatial] 您好 这个网站进不去啊 (Issue #34) |

Thanks for reporting. The app has been rebooted. It should be working now.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
