### ISSUE TITLE
Adding Timelapse GIF to the map

### ISSUE THREAD

**Issue by MuhammedM294** [giswqs/streamlit-geospatial#37]
Hi There!

I'm working on  app which enables the user to create timelapse from Sentinel-1 SAR.  When I try to add the gif to the app map, it doesn't show on the existing map, and to show it,  I need to use map.to_streamlit again to show any updates on the map and that generate a new map. So finally, I have two maps: the app map and another map with the gif created. 
Is there anyway to add the gif to the map?
 
Also, after using the geemap.Map method (to_streamlit), the map instance loses all its interactive fuctionalities. I can't add any ipyleaflet controls or any widget control.

**Comment by giswqs** [comment]
Streamlit does not support map bidirectional functionality. The map rendered in streamlit is just a static HTML file. All custom ipyleaflet controls won't show up on the map. If you want bidirectional functionality, try voila. Check out the links below. 

- https://geemap.org/notebooks/27_timelapse_app/
- https://geemap.org/notebooks/28_voila/
- https://www.youtube.com/playlist?list=PLAxJ4-o7ZoPccOFv1dCwvGI6TYnirRTg3
