### ISSUE TITLE
Authentication problems with GEE in Streamlit

### ISSUE THREAD

**Issue by MartaNoInercial** [giswqs/streamlit-geospatial#4]
First of all, thank you for sharing this awesom material.

I have a problem when adding a GEE leafmap in a deployed Streamlit app: it does not display. It asks for a code given by a webside, I have the code but there is no box where to paste it. How can I solve this problem? 

Thank you!

**Comment by giswqs** [comment]
You can find the token in the following file path:

```
Windows: C:\Users\USERNAME\.config\earthengine\credentials
Linux: /home/USERNAME/.config/earthengine/credentials
MacOS: /Users/USERNAME/.config/earthengine/credentials
```

Open the file and copy the token 
![](https://i.imgur.com/wDQ5WiS.png)

Go to https://share.streamlit.io and set it as a secret for your app.
![](https://i.imgur.com/enB1Ljj.png)

**Comment by MartaNoInercial** [comment]
Thank you so much!
