### ISSUE TITLE
App for creating maps of hurricane tracks

### ISSUE THREAD

**Issue by giswqs** [giswqs/streamlit-geospatial#46]
The [tropycal](https://github.com/tropycal/tropycal) package is very interesting. It would be great to create an app for this. 

- https://tropycal.github.io/tropycal/index.html
- https://github.com/tropycal/tropycal
![](https://tropycal.github.io/tropycal/_images/dorian.png)

**Comment by navigatio1** [comment]
I agree - it could be very useful for school students studying tropical storms using GIS
