### ISSUE TITLE
visualize month-to-month variations

### ISSUE THREAD

**Issue by ZCWang95** [giswqs/streamlit-geospatial#5]
It seems the current version only provides the visualization of year-to-year variations. While this is already an amazing tool, it would be great if later versions could allow users to create time-lapses at monthly or seasonal scales.

**Comment by giswqs** [comment]
This feature is coming soon. It has been implemented in geemap. I am adding it to the streamlit app. https://github.com/giswqs/geemap/pull/745

**Comment by giswqs** [comment]
This feature has been implemented. You can now create quarter/monthly Landsat/Sentinel-2 timelapse. 

![monthly](https://user-images.githubusercontent.com/5016453/141669179-8c072398-3ebd-4def-87f4-27248b560a1a.gif)

**Comment by ZCWang95** [comment]
Thank you! This is really cool!

Zhaocheng Wang, Ph.D. Candidate
Hydrosystems Engineering
School of Sustainable Engineering and the Built Environment
Arizona State University
E-mail: ***@***.***
