### ISSUE TITLE
is the site down?

### ISSUE THREAD

**Issue by knwin** [giswqs/streamlit-geospatial#53]
got error message on firefox "Error running app. If this keeps happening, please [contact support](https://github.com/giswqs/streamlit-geospatial/issues/new)."

**Comment by giswqs** [comment]
The app works fine on my end. If you are still experiencing issues, please provide detailed parameters you used that can produce the issue.

**Comment by knwin** [comment]
I browse to https://streamlit.geemap.org/

I have enabled cookies for the site but I still keep getting below error message.
```
The page isn’t redirecting properly

An error occurred during a connection to geospatial.streamlitapp.com.

    This problem can sometimes be caused by disabling or refusing to accept cookies.

[Try Again]
```
