### ISSUE TITLE
URL https://geospatial.streamlitapp.com/ also leading to "Error running app" 

### ISSUE THREAD

**Issue by frizatch** [giswqs/streamlit-geospatial#55]
Hi Qiusheng,

Thanks again for building this amazing tool. You pointed me to the newer URL, but I'm now again encountering the same error message. Interestingly, the .com URL did work for me initially (!?!).

![image](https://user-images.githubusercontent.com/20845777/177652401-6af09576-834e-408e-a684-7f1a15820d24.png)

I noticed in the latest closed issues that the geospatial streamlit app is working on your end so this may be hard to track down. I have tried all the following and am landing at "Error running app" every time:

Mac OS High Sierra 10.13.6, both Chrome and Safari (I cleared my cache and this still happened)
Windows 10 Enterprise, Chrome, Microsoft Edge and Firefox

I wonder if you check it on a machine where you've not done the development of the application if you'll run into the same error?

Cheers and thanks,
Diane

**Comment by giswqs** [comment]
I just rebooted the app. It should be working now. It appears that sometimes the app crashes due to large downloads.
