### ISSUE TITLE
Reporting an a potential action that caused crashing

### ISSUE THREAD

**Issue by frizatch** [giswqs/streamlit-geospatial#56]
Hi Qiusheng,

It's likely the app needs rebooting again as the "Error running app. If this keeps happening, please [contact support](https://github.com/giswqs/streamlit-geospatial/issues/new)" is appearing once again.

I wanted to let you know of an interaction I had that could've been pure coincidence:

I was using Chrome on my mac and accessing https://geospatial.streamlitapp.com/ to show it to someone. I was navigating the map on the timelapse feature and all seemed fine, but as soon as I started drawing a rectangular bounding box to delineate a geojson, the app crashed and immediately went to the error page.

Maybe this information can help with any troubleshooting. (?)

**Comment by giswqs** [comment]
Thank you for reported. I just submitted a potential bug fix. It should be working now. Feel free to reopen this issue if you are still experiencing errors.
