### ISSUE TITLE
Issues trying to create a timelapse

### ISSUE THREAD

**Issue by luispertovt** [giswqs/streamlit-geospatial#7]
GOES-16/17, La Palma Island. From a week to any other option, any size, always the same message: "Something went wrong, either the ROI is too big or there are no data available for the specified date range. Please try a smaller ROI or different date range."

![image](https://user-images.githubusercontent.com/75147172/141650413-2957e73f-bd15-4057-8065-67d93a765210.png)

**Comment by giswqs** [comment]
Try it with a time range less then 24 hours. GOES has a 10-min frequency, 144 frames per day. That's a lot of data.

**Comment by luispertovt** [comment]
Thanks for the answerd,I've tried, doesn't work, message received:
Exception: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs.Traceback:File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/script_runner.py", line 354, in _run_script exec(code, module.__dict__)File "/app/streamlit-geospatial/app.py", line 37, in <module> apps.run()File "/app/streamlit-geospatial/multiapp.py", line 63, in run functions[titles.index(title)]()File "/app/streamlit-geospatial/apps/timelapse.py", line 609, in app overlay_opacity=overlay_opacity,File "/home/appuser/venv/lib/python3.7/site-packages/geemap/timelapse.py", line 2085, in goes_timelapse raise Exception(e)The same has happened before.:I've seen animations of the entire Africa continent for months and doesn't work for a week in a small area?I also tried limiting the hours (just one hour a day). Unfortunately, neither option works.Cheers,

-- 
Luis
"Keep your face always toward the sunshine- and shadows will fall behind you."
                                                                Walt Whitman



 

    El sábado, 13 de noviembre de 2021 10:08:44 GMT-6, Qiusheng Wu ***@***.***> escribió:  
 
 


Try it with a time range less then 24 hours. GOES has a 10-min frequency, 144 frames per day. That's a lot of data.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by giswqs** [comment]
It seems only a tiny portion of GOES-16 covers La Palma Island. After adjusting the ROI, I was able to create the timelapse covering the island, evening the GIF quality is a bit low. 

![image](https://user-images.githubusercontent.com/5016453/143533255-83e04459-88a0-4f19-bccc-140f3d7751a5.png)

![](https://i.imgur.com/1tuwuIy.png)
