### ISSUE TITLE
Error creating time lapse

### ISSUE THREAD

**Issue by Sensing11** [giswqs/streamlit-geospatial#8]
Hi

I received following error while creating timelapse. Can you pls help. Thank you

Exception: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs.
Traceback:
File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
File "/app/streamlit-geospatial/app.py", line 37, in <module>
    apps.run()
File "/app/streamlit-geospatial/multiapp.py", line 63, in run
    functions[titles.index(title)]()
File "/app/streamlit-geospatial/apps/timelapse.py", line 493, in app
    mp4=mp4,
File "/home/appuser/venv/lib/python3.7/site-packages/geemap/timelapse.py", line 1915, in landsat_timelapse
    raise Exception(e)

**Comment by giswqs** [comment]
Please provide the settings that can reproduce the error.

**Comment by Sensing11** [comment]
Hi Qiusheng

I used Chrome browser to access website.

Attached AOI was submitted with standard setting 5 frames per sec, Landsat timelapse, NIR/Red/Green, 1990-2021 and rest default settings.

Thank you


Mustak Shaikh
Principal Remote Sensing

Water Analytics | Department of Planning, Industry and Environment
T 02 8838 7526, 0403 770 175  |  E ***@***.******@***.***>
4PSQ Level 30,12 Darcy St Parramatta NSW 2150
www.dpie.nsw.gov.au<http://www.dpie.nsw.gov.au/>


[cid:d4303523-9165-4c0f-beb0-53d26d6235e5]

<http://www.dpie.nsw.gov.au/>


Our Vision: Together, we create thriving environments, communities and economies.

The Department of Planning, Industry and Environment acknowledges that it stands on Aboriginal land. We acknowledge the traditional custodians of the land and we show our respect for elders past, present and emerging through thoughtful and collaborative approaches to our work, seeking to demonstrate our ongoing commitment to providing places in which Aboriginal people are included socially, culturally and economically.

________________________________

**Comment by giswqs** [comment]
The AOI did not come through. Please upload it on GitHub. Email attachment does not seems to work with GitHub
