### ISSUE TITLE
I can not access https://geospatial.streamlitapp.com/

### ISSUE THREAD

**Issue by Pheaktra-max** [giswqs/streamlit-geospatial#81]
Dear sir/madam,

I want to create a satellite timelapse in Tonle Sap Lake area, 
but I have face problem with your website https://geospatial.streamlitapp.com/
could you solve it?
best regards
pheaktra

**Comment by joaocps** [comment]
+1 here @giswqs

**Comment by vprint** [comment]
Same here

**Comment by giswqs** [comment]
App rebooted.
