### ISSUE TITLE
double click on the radio button when switch back & forth between pages

### ISSUE THREAD

**Issue by huamichaelchen** [giswqs/streamlit-geospatial#9]
I think the issue is with the `app_state` assignment.

**Comment by giswqs** [comment]
This is a known issue related to https://github.com/upraneelnihar/streamlit-multiapps/issues/2. The reason for using `st.experimental_set_query_params(**app_state)` is to create direct link to preselected sidebar menu, such as the link below. Changing it to `t.experimental_set_query_params(**st.session_state.to_dict())` would lose the direct link functionality. 

https://share.streamlit.io/giswqs/streamlit-geospatial/app.py?radio=Home&page=Create+Timelapse

**Comment by huamichaelchen** [comment]
Ah, I see. Yup, the same thing happening on my end. Let me poke around ;)

**Comment by huamichaelchen** [comment]
> This is a known issue related to [upraneelnihar/streamlit-multiapps#2](https://github.com/upraneelnihar/streamlit-multiapps/issues/2). The reason for using `st.experimental_set_query_params(**app_state)` is to create direct link to preselected sidebar menu, such as the link below. Changing it to `t.experimental_set_query_params(**st.session_state.to_dict())` would lose the direct link functionality.
> 
> https://share.streamlit.io/giswqs/streamlit-geospatial/app.py?radio=Home&page=Create+Timelapse

Not quite sure what happened... But this is how I get it to work for both the "direct link visit" issue and avoid the "double click on the radio button to switch back and forth" issue. 

```
        pressed = st.session_state.radio 
        app_state["page"] = pressed

        st.experimental_set_query_params(**st.session_state.to_dict())
        functions[titles.index(title)]()
```

It seems that `app_state["page"] = st.session_state.radio` is the culprit? Because when I have the following: 

```
        app_state["page"] = st.session_state.radio
        st.experimental_set_query_params(**app_state)
```

Direct visit works, but I have to click on the radio button twice in order to switch to a separate page. It almost as if `app_state["page"] = st.session_state.radio` assignment ignored the first time a radio button is pressed.

Frankly, a bit confused...
