### ISSUE TITLE
Fail to deploy on Streamlit

### ISSUE THREAD

**Issue by KHwong12** [giswqs/streamlit-geospatial#94]
Hi Dr. Wu, first thing first, many thanks for creating this fascinating web app.

I followed [your blog](https://blog.streamlit.io/creating-satellite-timelapse-with-streamlit-and-earth-engine/#how-to-deploy-an-earth-engine-app-to-streamlit-cloud), created a [fork of this repo](https://github.com/KHwong12/streamlit-geospatial) and tried to deploy a copy of the app to Streamlit. I followed the steps and created a token and added it as an environment variable.

However, the deploy log still requires me to authenticate GEE, and the error `Earth Engine client library not initialized.` appears when I try to upload the study boundary. 

Following are the screenshots of the secret token configuration and the deploy log. Is there something I did wrong when configuring the app/authenticating GEE?

---

#### Setting token as environment variable

<img width="1268" alt="secret-token" src="https://user-images.githubusercontent.com/29334677/201335446-e30128b5-363a-4fe8-ab72-f14bc9afb029.png">

#### Error when adding study boundary

https://user-images.githubusercontent.com/29334677/201335429-5c5abb14-6ddb-4cc3-b0fa-4346ffe2ae53.mp4

#### Deploy log of error

<img width="1389" alt="deploy-log-require-auth" src="https://user-images.githubusercontent.com/29334677/201335664-b45364d0-ff44-4086-9146-5101c67dbc26.png">

**Comment by giswqs** [comment]
The `EARTHENGINE_TOKEN` should look like this. Use `ee.Authenticate()` on your computer to generate a new token if needed. 

![image](https://user-images.githubusercontent.com/5016453/202614472-7181aa69-e70b-4abc-a802-a4e57208023c.png)

**Comment by KHwong12** [comment]
Thanks! The app works perfectly now. Originally I thought the `EARTHENGINE_TOKEN` only includes the `refresh_token` part of the JSON.

**Comment by frizatch** [comment]
Greetings! I too am trying to follow that [blog](https://blog.streamlit.io/creating-satellite-timelapse-with-streamlit-and-earth-engine/#how-to-deploy-an-earth-engine-app-to-streamlit-cloud) and create a working app by forking that repo, but I am getting stuck earlier at the `ee.Authenticate()` step. I get an error that ends with:

`Exception: gcloud command not found. Please ensure that gcloud is installed.`
`More information: https://developers.google.com/earth-engine/guides/python_install`

I eventually landed here but I'm feeling a bit lost as I don't think this is correct (I'm building environments in Anaconda): https://cloud.google.com/sdk/docs/install

Also, I tried this package but it is no longer available from conda-forge according to my install attempt:
https://anaconda.org/conda-forge/google-cloud-sdk

Do you have a quick hint as to where I might look to fix the authentication issue with gcloud?

Thanks much!
